In [1]:
import pandas as pd

df = pd.read_csv("messy_sales.csv")

print(df.shape)
display(df.head(10))
print(df.dtypes)

(300, 6)

   order_id        date   product  price  qty    zip
0      1254  04/06/2026       mug  11.36    4  60614
1      1057  2026-05-30   charger  14.79    3  30303
2      1150  05/06/2026       mug   5.50    1  10001
3      1066  05/30/2026  notebook    NaN    1  98101
4      1114  04/06/2026    webcam  45.59    4  90405
5      1280  04/22/2026   pen set    NaN    4  30303
6      1204  04/18/2026   charger   8.41    2   2134
7      1249  2026-05-15  keyboard  75.04    4  90405
8      1037  2026-05-19       mug   9.31    2  60614
9      1177  2026-05-13       mug  10.11    3  90210

order_id      int64
date            str
product         str
price       float64
qty           int64
zip           int64
dtype: object

Observations: 3 problems I can see with this data
1. Date, not consistent formatting.
2. Price column missing data.
3. Zip codes are missing numbers (0).

In [2]:
df.isna().sum()

order_id     0
date         0
product      0
price       12
qty          0
zip          0
dtype: int64

In [3]:
fill_value = df["price"].median()
df["price"] = df["price"].fillna(fill_value)

In [4]:
print("Median price used:", fill_value)
df.isna().sum()

Median price used: 37.53

order_id    0
date        0
product     0
price       0
qty         0
zip         0
dtype: int64

In [5]:
df.isna().sum()

order_id    0
date        0
product     0
price       0
qty         0
zip         0
dtype: int64

In [6]:
print(df.duplicated().sum())
df = df.drop_duplicates()

8

In [7]:
print("Shape after removing duplicates:", df.shape)

Shape after removing duplicates: (292, 6)

In [9]:
df["zip"] = df["zip"].astype(str).str.zfill(4)

In [10]:
print(df["zip"].head(10))

0    60614
1    30303
2    10001
3    98101
4    90405
5    30303
6     2134
7    90405
8    60614
9    90210
Name: zip, dtype: str

In [12]:
df["zip"] = df["zip"].astype(str).str.zfill(5)

In [13]:
print(df["zip"].head(10))

0    60614
1    30303
2    10001
3    98101
4    90405
5    30303
6    02134
7    90405
8    60614
9    90210
Name: zip, dtype: str

In [14]:
df["date"] = pd.to_datetime(df["date"], format="mixed")

In [15]:
df.dtypes

order_id             int64
date        datetime64[us]
product                str
price              float64
qty                  int64
zip                    str
dtype: object

In [17]:
df[df["qty"] > 80]

Empty DataFrame
Columns: [order_id, date, product, price, qty, zip]
Index: []

In [20]:
negative_qty = df[df["qty"] < 0]

In [21]:
negative_qty

     order_id       date    product  price  qty    zip
202      1140 2026-04-18     webcam  38.69   -5  98101
262      1233 2026-05-09  desk lamp  22.64   -4  10001
297      1025 2026-04-27   keyboard  47.30   -2  02116

In [22]:
df["return_flag"] = df["qty"] < 0

In [23]:
display(df[df["return_flag"]])

     order_id       date    product  price  qty    zip  return_flag
202      1140 2026-04-18     webcam  38.69   -5  98101         True
262      1233 2026-05-09  desk lamp  22.64   -4  10001         True
297      1025 2026-04-27   keyboard  47.30   -2  02116         True

In [25]:
df.to_csv("sales_clean.csv", index=False)

In [ ]:
Cleaning log: 
-Started with 300 rows.
-There were 12 missing prices identified, used the median price to fill.
-Identified 8 duplicated rows, removed the duplicated rows.
-Zip codes were missing the zeros, added zeros to zip codes.
-Some negative quantities identified, I chose to treat them as returns (returns to flag). I chose this option because when reviewing the data it appears the negative quanities relate to an order placed earlier. 
For example I saw that order 1250 ordered April 30, 2026 ordered 5 desk lamps with a zip code of 10001 followed by a order 1233 on May 09,2026 showing -4 quanitity from the same zip code of 10001.
With this finding and without more information I feel that the orders are related and to be kept in the data with the added return flag for enteries.
A wrong choice can mislead a business decision on how many of what items to order, as it can cause issues in inventory.

In [ ]:
AI USE: Chatgpt
- troubleshooting opening Jupyterlab, was receiving windows block and then notebook wouldn't update (I accidentally closed miniforger)
- used for flagging returns and saving CSV file